#!/bin/bash
# Generate agent extensions (quick aliases and slash commands) based on systemprompts

set -euo pipefail

PROJECT_ROOT="${1:-$(pwd)}"
PROMPTS_DIR="${PROJECT_ROOT}/.claude/systemprompts"
COMMANDS_DIR="${PROJECT_ROOT}/.claude/commands"

if [[ ! -d "$PROMPTS_DIR" ]]; then
    echo "Error: No systemprompts directory found at $PROMPTS_DIR"
    exit 1
fi

# Ensure commands directory exists
mkdir -p "$COMMANDS_DIR"

echo "Generating agent extensions for: $PROJECT_ROOT"
echo ""

# Generate quick aliases file
ALIASES_FILE="${PROJECT_ROOT}/.claude/generated-aliases.sh"
cat > "$ALIASES_FILE" << 'EOF'
# Auto-generated quick aliases for Claude agents
# Generated by: .claude/scripts/generate-agent-extensions.sh
# Source this file from your .zshrc after the main Claude functions

EOF

# Generate slash commands and aliases for each agent
for prompt_file in "$PROMPTS_DIR/"*.md; do
    if [[ -f "$prompt_file" ]]; then
        agent_name="$(basename "$prompt_file" .md)"
        
        # Skip README files
        if [[ "$agent_name" == "README" ]]; then
            continue
        fi
        
        # Generate quick alias
        echo "# Quick alias for $agent_name agent" >> "$ALIASES_FILE"
        echo "ca-${agent_name}() { ca ${agent_name} --yolo \"\$@\"; }" >> "$ALIASES_FILE"
        echo "" >> "$ALIASES_FILE"
        
        # Generate update context slash command if it doesn't exist
        context_cmd_file="${COMMANDS_DIR}/update-${agent_name}-context.md"
        if [[ ! -f "$context_cmd_file" ]]; then
            cat > "$context_cmd_file" << EOF
# Update ${agent_name^} Context

Review your session and update \`.claude/contexts/${agent_name}_context.md\`.

Focus on:
- Activities completed in this session
- New discoveries or insights
- Tasks that remain pending
- Configuration changes made
- Issues encountered and resolved
- Next steps or follow-ups needed

Remember to:
- Remove completed tasks
- Update current focus areas
- Keep information actionable
- Remove outdated content
EOF
            echo "Created slash command: /update-${agent_name}-context"
        fi
    fi
done

echo "" >> "$ALIASES_FILE"
echo "# Function to list all quick aliases" >> "$ALIASES_FILE"
echo "ca-list-aliases() {" >> "$ALIASES_FILE"
echo "    echo 'Available quick aliases (all include --yolo):'" >> "$ALIASES_FILE"
echo "    compgen -A function | grep '^ca-' | grep -v 'ca-list' | sort" >> "$ALIASES_FILE"
echo "}" >> "$ALIASES_FILE"

chmod +x "$ALIASES_FILE"

echo ""
echo "Generated files:"
echo "- ${ALIASES_FILE}"
echo ""
echo "To use the generated aliases, add this to your .zshrc:"
echo "source \"${ALIASES_FILE}\""
echo ""
echo "Quick aliases created:"
grep "^ca-.*() {" "$ALIASES_FILE" | sed 's/() {.*//' | sort
echo ""
echo "Run 'ca-list-aliases' to see all available quick aliases"